version: "3.8"

services:
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    entrypoint: ["bash", "-c", "airflow db init && airflow webserver & airflow scheduler"]
