version: "3.8"

services:
  airflow:
    image: apache/airflow:latest
    container_name: airflow
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__WEBSERVER__RBAC=True  # Enable RBAC
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__SECRET_KEY=temporarysecretkey
      - AIRFLOW__WEBSERVER__LOGIN_DISABLED=False  # Enable login
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts 
      - ./credentials:/opt/airflow/credentials
      - ./dataset:/opt/airflow/dataset
    ports:
      - "8080:8080"
    entrypoint: ["bash", "-c", "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin && airflow webserver & airflow scheduler"]